client_config_backend: file
client_config:
    client_id: 390183797322-f8pfajhmncng2cnnt8ggklt7umqousnu.apps.googleusercontent.com
    client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
    - https://www.googleapis.com/auth/drive